# Site settings
title: Hack Clock
# Architect Theme : https://github.com/pages-themes/architect
theme: jekyll-theme-architect
email: john@deckerego.net
description: >
  A hackable alarm clock, built for experimentation and learning
baseurl: ""
url: "http://hackclock.deckerego.net"
twitter_username: deckerego
github_username:  deckerego
hackaday_url: https://hackaday.io/project/3413-hack-ready-alarm-clock
hackaday_username: deckerego
#google_analytics: UA-32628230-2

# Build settings
markdown: kramdown
